# Generated by Django 4.1.3 on 2024-02-12 11:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticlesName', models.CharField(max_length=1000)),
                ('ArticleImage', models.ImageField(blank=True, null=True, upload_to='media/ArticlesImage/')),
                ('ArticleLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Message', models.TextField(blank=True, max_length=5000, null=True)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('Email', models.EmailField(default='@gmail.com', max_length=254)),
                ('Place', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ContactMe',
            },
        ),
        migrations.CreateModel(
            name='Hob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=1000)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/HobImage/')),
                ('HobLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hob',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.CharField(max_length=200)),
                ('UniversityPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('UniversityImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('UniversityLink', models.CharField(blank=True, max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='user name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'UniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='UdsmUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'UdsmUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='UdomUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'UdomUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='@gmail.com', max_length=100)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('TeacherImage', models.ImageField(blank=True, null=True, upload_to='media/StudentImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(max_length=200, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(default='@gmail.com', max_length=100)),
                ('Phone', models.CharField(default='+255', max_length=13)),
                ('StudentImage', models.ImageField(blank=True, null=True, upload_to='media/StudentImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='MustUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'MustUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(blank=True, max_length=100, null=True)),
                ('Year', models.CharField(blank=True, default='First Year', max_length=100, null=True)),
                ('ModuleImage', models.ImageField(blank=True, null=True, upload_to='media/ModuleImage/')),
                ('ModuleLink', models.CharField(blank=True, max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ManyToManyField(max_length=200, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=500)),
                ('StudentPlace', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('StudentImage', models.ImageField(blank=True, null=True, upload_to='media/Hob/')),
                ('Github', models.CharField(blank=True, default='www.github.com', max_length=1000, null=True)),
                ('Youtube', models.CharField(blank=True, default='www.youtube.com', max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, default='juniordimoso@gmail.com', max_length=500, null=True)),
                ('Instagram', models.CharField(blank=True, default='www.instagram.com', max_length=1000, null=True)),
                ('Whatsapp', models.CharField(blank=True, default='www.whatsapp.com', max_length=1000, null=True)),
                ('Phone', models.CharField(blank=True, default='+255', max_length=13, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CategoryName', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.hob')),
            ],
            options={
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='DitUniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseImage', models.ImageField(blank=True, null=True, upload_to='media/UniversityImage/')),
                ('CourseDepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseCapacity', models.IntegerField(blank=True, null=True)),
                ('CourseLink', models.CharField(blank=True, default='USMA/', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'DitUniversityCourses',
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='How to start learning ---------', max_length=1000)),
                ('WrittenBy', models.CharField(blank=True, default='Dimoso Junior', max_length=100, null=True)),
                ('ArticleBody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ArticleImage', models.ImageField(blank=True, null=True, upload_to='media/ArticlesImage/')),
                ('Github', models.CharField(blank=True, default='www.github.com', max_length=1000, null=True)),
                ('Youtube', models.CharField(blank=True, default='www.youtube.com', max_length=1000, null=True)),
                ('year', models.CharField(blank=True, default='2023', max_length=100, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/ArticlesPDF/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('ArticlesName', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.articles')),
            ],
            options={
                'verbose_name_plural': 'ArticlesCategory',
            },
        ),
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=500)),
                ('StudentName', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=50)),
                ('ProjectBody', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/ProjectsPDF')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('ProjectImage', models.ImageField(blank=True, null=True, upload_to='media/ProjectImage/')),
                ('StudentEmail', models.EmailField(blank=True, default='youremail@gmail.com', max_length=100, null=True)),
                ('StudentPhoneNumber', models.CharField(blank=True, default='+255', max_length=50, null=True)),
                ('Github', models.CharField(blank=True, default='https://github.com/dimosojunior/', max_length=1000, null=True)),
                ('Youtube', models.CharField(blank=True, default='www.youtube.com', max_length=1000, null=True)),
                ('WhatsappLink', models.CharField(blank=True, default='www.whatsapp.com', max_length=1000, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CourseName', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universitycourses')),
                ('university', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.universities')),
            ],
            options={
                'verbose_name_plural': 'AllProjects',
            },
        ),
    ]
